spring.application.name=NailsBot

server.port=8080

logging.level.ru.vilen=debug
logging.pattern.console=%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] - %msg%n

bot.name=${BOT_NAME}
bot.token=${BOT_TOKEN}
bot.admin=${BOT_ADMIN}
bot.admin-link=${ADMIN_LINK}
bot.avito-link=${AVITO_LINK}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update