spring.application.name=NailsBot

server.port=8080

logging.level.ru.vilen=debug
logging.pattern.console=%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] - %msg%n

bot.name=LiannaNailsBot
bot.token=8015804622:AAGE0oH5DurZP852iIQ6TyHRmJWQeg4bAS4